### ISSUE TITLE
Open AI API Token does not have access to GPT-4v even when I'm tier 1 account 

### ISSUE THREAD

**Issue by maimand** [davidmigloz/pixels2flutter#81]
<img width="834" alt="image" src="https://github.com/davidmigloz/pixels2flutter/assets/42661871/9a4c6d29-a0fa-4c25-a064-21027bec61e4">
<img width="1046" alt="image" src="https://github.com/davidmigloz/pixels2flutter/assets/42661871/91c6b7bb-9a7c-4238-8437-db98275af159">

Need help with the Open AI API token

**Comment by davidmigloz** [comment]
Hey @maimand ,

I've just migrated the app [from GPT-4V to GPT-4o](https://github.com/davidmigloz/pixels2flutter/commits/main/) (their latest flagship model). Please try again to see if the error is resolved.

Otherwise, you can open the browser developer tools > Network and see which specific error the OpenAI API is returning.

Cheers.

**Comment by wailashraf71** [comment]
Same issue with GPT-4o

**Comment by davidmigloz** [comment]
@wailashraf71 Which error do you get from the OpenAI API?
